language: php

php:
    - 5.6

matrix:
  allow_failures:
    - php: nightly

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source

script: phpunit
